apiVersion: v1
kind: Pod
metadata:
 name: podx
spec:
 containers:
 - name: busybox
   image: busybox:1.28
   command: [ "sh", "-c", "echo 'Hello AppArmor!' && sleep 2h" ]
 nodeSelector:
   kubernetes.io/hostname: k8s-worker1
