apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: couchdb
  name: couchdb
spec:
  replicas: 1
  selector:
    matchLabels:
      run: couchdb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: couchdb
    spec:
      containers:
      - image: couchdb
        name: couchdb
        securityContext:
          {'capabilities': {'add': ['NET_BIND_SERVICE', 'SYS_ADMIN'], 'drop': ['all']}, 'privileged': True, 'readonlyRootFilesystem': False, 'runAsUser': 65535}
        resources: {}

